--There are two functions that will install mods, ServerModSetup and ServerModCollectionSetup. Put the calls to the functions in this file and they will be executed on boot.

--ServerModSetup takes a string of a specific mod's Workshop id. It will download and install the mod to your mod directory on boot.
	--The Workshop id can be found at the end of the url to the mod's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=350811795
	--ServerModSetup("350811795")
	--Camp Security (Protegeix el campament de que es cremi) 
	ServerModSetup("1416161108")
	--DST Storm Cellar (permet construir la estructura storm cellar que es com un chester gegant fireproof)
	ServerModSetup("382177939")
	--Increased Stack size (permet stackejar els materials fins a 99) 
	ServerModSetup("374550642")
	--Extra Equip Slots (Updated) (afegeix un slot mes de equipo de motxilla i de amuleto)
	ServerModSetup("1818688368")
	--Show me (Origin) (Mostra contenidors amb el mateixos objectes que portes a la ma, dona info de temps de recreixement de plantes i crops, dona info de les eines i del menjar, mostra la vida dels bitxos... amb aquest deixa de fer falta health info, display food values i finder)
	ServerModSetup("666155465")
	--Simple Health Bar DST (mostra la barra de vida i mostra el dany / heal, es pot configurar per a veure lo dels corets. Deixa de fer falta health info)
	ServerModSetup("1207269058")
	--Quick drop (permet llençar les coses al lloc en el que estás sense haver de arrastrar a fora de l'inventari) 
	ServerModSetup("856487758")
	--Glowing Portal (Fa que el portal de resurrect brilli, util per quan suneix gent i es de nit, sino moren al instant)
	ServerModSetup("585654889")
	--Quick Pick (permet agafar les coses de forma mes rapida)  
	ServerModSetup("501385076")
	--Let me sprint! (Permet sprintar mantent polsat shift amb cost de gana)
	ServerModSetup("2340409563")
	--Global Positions (comparteix el mapa entre els jugadors i mostra la seva posicio a temps real al mapa)
	ServerModSetup("378160973")
	--DST Where is my beefalo (mostra la localització del beefalo y altres mobs, incloent bosses)
	ServerModSetup("347360448")
	--Craftable Gears - Configurable! (permet craftejar gears al menu refine i escollir quins materials fan falta per a la recepta) 
	ServerModSetup("817025783")
	--No thermal stone durability (fa que les pedres termiques no s'espatllin)
	ServerModSetup("466732225")
	--Digable Reeds (permet transplantar les plantes del pantano de papiro)
	ServerModSetup("367304592")
	--DST easy resurrection shelter (permet reviure a un foc o bé construir el resurrection shelter per a reviure) 
	ServerModSetup("352499675")
	--Only fertilize once (fertilitza les plantes nomes un cop) 
	ServerModSetup("471111069")
	--Personal chesters (afegeix un chester a cada jugador)
	ServerModSetup("463740026")
	--A Big Bag 大背包 1.5 (permet craftejar una mochila de 64 espais)
	ServerModSetup("810443397")
	--Infinite Tent uses (fa que les tendes per dormir no es desgastin)
	ServerModSetup("356930882")
	--Tools are fuels (permet llençar tools al foc, útil per eines amb percentatge low)
	ServerModSetup("599498678")
	--Mineable Gems (afegeix drop de una gema al petar una roca)
	ServerModSetup("380423963")
	--Large Boats (permet construir vaixells molt mes grans) 
	ServerModSetup("1839858501")
	--Moving Box (Updated) (permet empaquetar estructures per a moureles)
	ServerModSetup("2353205177")
	--Crash Bandicoot (Afegeix fruta woompa pel mapa i la possibilitat d'escollir a crash com a personatge. crash r¡cupera sanity de forma pasiva i porta sempre a aku-aku de acompanyant, pero aquest te una sanity aura de -100 :/ )
	ServerModSetup("382501575")


--ServerModCollectionSetup takes a string of a specific mod's Workshop id. It will download all the mods in the collection and install them to the mod directory on boot.
	--The Workshop id can be found at the end of the url to the collection's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=379114180
	--ServerModCollectionSetup("379114180")
